// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHF4zGICS98eVeyJpsaO5govUnivmaST0',
    appId: '1:61329876360:web:f9e24d83e86ed890b9863d',
    messagingSenderId: '61329876360',
    projectId: 'proyecto-a0d6e',
    authDomain: 'proyecto-a0d6e.firebaseapp.com',
    storageBucket: 'proyecto-a0d6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVraAZOJAZSd4YlmnUyuFQBVauiMenN3I',
    appId: '1:61329876360:android:de9d13fba42a5d5ab9863d',
    messagingSenderId: '61329876360',
    projectId: 'proyecto-a0d6e',
    storageBucket: 'proyecto-a0d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6ToyknELO6BP80OWjllQTDMjJhiKM3c',
    appId: '1:61329876360:ios:87b1f9d5d90efb2ab9863d',
    messagingSenderId: '61329876360',
    projectId: 'proyecto-a0d6e',
    storageBucket: 'proyecto-a0d6e.appspot.com',
    iosClientId: '61329876360-62r3dpeltmpv8le6f6vi761rrp2adm2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ6ToyknELO6BP80OWjllQTDMjJhiKM3c',
    appId: '1:61329876360:ios:d64b84ce1687937cb9863d',
    messagingSenderId: '61329876360',
    projectId: 'proyecto-a0d6e',
    storageBucket: 'proyecto-a0d6e.appspot.com',
    iosClientId: '61329876360-427oc1oi4dhngg5qvbjsqbpf7soo9qr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectofinal.RunnerTests',
  );
}
